### PR TITLE
Add universal packaging for snaps

### PR DESCRIPTION
**Pull request by jamiedbennett**
##### ISSUE TYPE
 - Feature pull-request

##### DSTAT VERSION
```
Dstat 0.7.3
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/dstat/

Platform posix/linux2
Kernel 4.4.0-22-generic
Python 2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160413]

Terminal type: xterm-256color (color support)
Terminal size: 65 lines, 80 columns

Processors: 1
Pagesize: 4096
Clock ticks per secs: 100

internal:
	aio, cpu, cpu-adv, cpu-use, cpu24, disk, disk24, disk24-old, epoch, 
	fs, int, int24, io, ipc, load, lock, mem, mem-adv, net, page, page24, 
	proc, raw, socket, swap, swap-old, sys, tcp, time, udp, unix, vm, 
	vm-adv, zones
/usr/share/dstat:
	battery, battery-remain, condor-queue, cpufreq, dbus, disk-avgqu, 
	disk-avgrq, disk-svctm, disk-tps, disk-util, disk-wait, dstat, 
	dstat-cpu, dstat-ctxt, dstat-mem, fan, freespace, fuse, gpfs, 
	gpfs-ops, helloworld, innodb-buffer, innodb-io, innodb-ops, lustre, 
	md-status, memcache-hits, mysql-io, mysql-keys, mysql5-cmds, 
	mysql5-conn, mysql5-innodb, mysql5-io, mysql5-keys, net-packets, nfs3, 
	nfs3-ops, nfsd3, nfsd3-ops, nfsd4-ops, nfsstat4, ntp, postfix, power, 
	proc-count, qmail, redis, rpc, rpcd, sendmail, snmp-cpu, snmp-load, 
	snmp-mem, snmp-net, snmp-net-err, snmp-sys, snooze, squid, test, 
	thermal, top-bio, top-bio-adv, top-childwait, top-cpu, top-cpu-adv, 
	top-cputime, top-cputime-avg, top-int, top-io, top-io-adv, 
	top-latency, top-latency-avg, top-mem, top-oom, utmp, vm-cpu, vm-mem, 
	vm-mem-adv, vmk-hba, vmk-int, vmk-nic, vz-cpu, vz-io, vz-ubc, wifi, 
	zfs-arc, zfs-l2arc, zfs-zil
```

##### SUMMARY
Add support for the universal package format: snaps. Created on Ubuntu 16.04 but runnable on most linux distros. See http://www.snapcraft.io. I am maintaining a snapped version of dstat in the Ubuntu store as dstat-jamiebennett but would be great to see an official version there.

To create the snap, using the snapcraft.yaml file just type:

snapcraft

in the dstat directory on a Ubuntu 16.04 system/VM. The snap can then be installed with sudo snap install dstat* or from the software store GUI once uploaded.

### CODE REVIEW

**Comment by dagwieers** [comment]
Can we put this file in a subdirectory instead ?

**Comment by jamiedbennett** [comment]
Yes, it can be moved. What dir would you like to see this in?

Regards,
Jamie.

**Comment by dagwieers** [comment]
I would liketo move everything packaging related to packaging/. So you can move your file to eg. `packaging/snap` (and the SPEC file then should go to `packaging/rpm`).

Would that make sense ?

**Comment by jamiedbennett** [comment]
Makes sense to me. Let me create a new PR.

Regards,
Jamie.

**Comment by dagwieers** [comment]
If there would be a standard for packaging files I could be convinced to use that standard ;-)
(Would be nice if somehow all packaging tools would use the same standard in their documentation too *hint*)

**Comment by dagwieers** [comment]
BTW Don't create a new PR ! Just update your branch, and push again.

**Comment by jamiedbennett** [comment]
OK, thanks.

And I agree on packaging, it has long been a struggle to have something cross-distro.

Regards,
Jamie.

**Comment by dagwieers** [comment]
Well, I doubt there realistically will ever be a single packaging standard for all distributions, but that's exactly why a standard for locating (different) packaging files is useful IMO.

**Comment by jamiedbennett** [comment]
Branch update. I didn't move the .spec file as I cannot verify that it won't break with the move on my machine here.

**Comment by dagwieers** [comment]
OK, I see the following issues:
- The file is now stored in ./packaging/ and not in ./packaging/snap/
- The file ./snapcraft.yaml still remains
- There is a new file ./packaging/python, is this file required ?

I don't mind merging this as-is, and then moving the file(s) to ./packaging/snap/ instead and removing ./snapcraft.yaml, if this would make your life easier.

**Comment by jamiedbennett** [comment]
On 20/07/16 at 03:04am, Dag Wieers wrote:
> OK, I see the following issues:
> 
>   • The file is now stored in ./packaging/ and not in ./packaging/snap/

Ah, I missunderstood, I can move it into a snap subdir.

>   • The file ./snapcraft.yaml still remains

umm, user error.

>   • There is a new file ./packaging/python, is this file required ?

This is needed as your dstat specifically references python2 instead of
python i.e. 

#!/usr/bin/env python2

The python symlink just links to the system python which is more commonly
available. I do not know why you specifically call out python2 but if this was
changed the python symlink for packaging would not be needed.

**Comment by dagwieers** [comment]
Right, I will merge this.

The reason for using `env python2` is to ensure python v2 is being used as Dstat does not support python v3. The problem with just doing `env python` is that one cannot be certain that this is python v2, it could be python v3. That is why most distributions by default also provide a python2 binary in order to be able to select it.

**Comment by dagwieers** [comment]
@jamiedbennett One more question. If you'd have the snapcraft command installed, do you have to do `snapcraft snap` inside the project directory to make the snap package ? I'd like to add a `make snap` target to the Makefile.

**Comment by dagwieers** [comment]
Makefile adapted according to the snapcraft documentation.

**Comment by jamiedbennett** [comment]
You have to run `snapcraft` from the packaging/snap dir which will produce a .snap file. This can then be installed on any supported distro with `sudo snap install dstat*.snap` or, if uploaded to a store like the ubuntu store (happy to help here) then it can be installed from the Gnome Software app or again from the command line.

**Comment by jamiedbennett** [comment]
(and thanks for the merge BTW)

**Pull request merged**
