### PR TITLE
intuitive color-coding overhaul

### PR DESCRIPTION
**Pull request by Osndok**
It's not expected that you accept this (I don't really know python, and this is my first hack on this codebase), but thought you might like to know the ideas:
- color spectrum semi-evenly ranges in frequency & brightness (red/orange/yellow/green/blue/violet)
- each variable dynamically senses it's maxima (so it takes some fluctuations to stabilize)
- all values color-coded by percentage (0 = gray/unnoticable, maximum/100% = bright red)
- "idle" column has the reverse logic (100% = gray/unnoticable, 0% = bright red)

### CODE REVIEW

**Comment by dagwieers** [comment]
I still like this conceptually.
This needs a discussion.

**Comment by scottchiefbaker** [comment]
I really like this conceptually too. I think we can do more with "gauge" based data to make it more visually apparent. This almost warrants an entire issue itself "Handle colors better". @Osndok would you like to contribute to that conversation?

Also, it's 2016 and I think there is the possibility of doing some cool things with 256 color terminals. On another project I wrote I did an evaluation of the most popular terminals in use and > 95% support 256 colors now.

**Comment by Osndok** [comment]
I found the graduated colorings really useful. One contraindication I found was that the terminal colors seemed to vary by platform (OSX vs Linux). The original patch was optimized for OSX, which is no longer my primary machine, so I have to qualms with the color selection being changed to the 256 pallette. OSX support may have moved on too by now, but if there is no easy way to detect (or differentiate) the terminal at run time (note you can't really use a uname or compile-time check due to SSH), then a flag/hole for dropping in 16-color (or OS/X support) might be appreciated by someone who is not me. I'm also not aware of a way to detect what the user's default terminal contrast theme is (white-on-black, black-on-white... colors?). Just some stray ramblings...

**Comment by scottchiefbaker** [comment]
#99 addresses light vs dark background detection. And `tput colors` will tell if you the terminal supports 256 colors or not. I think the tech to gather that data is available, we just need to implement it. This is a pretty big change though, so I want to hold off for now until the community has more change to offer feedback.

**Comment by dagwieers** [comment]
Probably 0.8 material, but we could already merge it using a (hidden) option for people to test an provide feedback.

**Pull request closed without merging**
