### PR TITLE
Correct 'black-on-white' to 'blackonwhite' in --help output

### PR DESCRIPTION
**Pull request by nckx**

### CODE REVIEW

**Comment by dagwieers** [comment]
I am a bit confused.
What is wrong with `--white-on-black` ?

**Comment by scottchiefbaker** [comment]
I think he's just trying to get help output to match the code? (not a python expert)

https://github.com/dagwieers/dstat/blob/master/dstat#L117

**Comment by nckx** [comment]
This is a blast from the past. :smile: Yes, I think I meant to say `Correct 'black-on-white' to [the] 'blackonwhite' [already present] in --help output`. That would have been more clear.

@scottchiefbaker: the other way around, actually: I'm making the code match the help output and the docs.

@dagwieers: I'm afraid I don't follow where `--white-on-black` comes from, sorry.

(Oh, and I don't think backwards compatibility is an issue: `--black-on-white` is used consistently throughout the rest of the code and documentation, `--blackonwhite` only once, and not visibly. Even *if* anyone were using `--black-on-white`, they'd be depending on undocumented behaviour — and you would have got a bug report by now.)

**Comment by scottchiefbaker** [comment]
Oh I see what's going on here. The `--help` output doesn't jive with what opts we accept. He's just trying to normalize all the naming. Good catch @nckx... merging.

**Comment by nckx** [comment]
Sigh. I *still* managed to swap the dashed and non-dashed versions in my last paragraph above. Fixed.

Thanks!

**Comment by dagwieers** [comment]
Personally, I would keep both versions. It tends to be one of the things people may get wrong from memory. But we spend already too much time on a silly option like this :-)

Thanks again for the fix !

**Pull request merged**
