### PR TITLE
Revert "Update plugins/dstat_mysql5_cmds.py"

### PR DESCRIPTION
**Pull request by pxsta**
This reverts commit fe5f91621f9c37671f359a75b40f4d6c29dd82e6.

I cannot understand why this file must take only two environment variables.
Other files about MySQL5 can take many environment variables.
Therefore, I guess that fe5f91621f9c37671f359a75b40f4d6c29dd82e6 is a mistake.

### CODE REVIEW

**Comment by scottchiefbaker** [comment]
@dagwieers is this something you're aware of? Should we merge this for 0.7.3, or push it back?

**Comment by scottchiefbaker** [comment]
If we do this it will revert part of #60 too, so we'll want to fix that.

**Comment by pxsta** [comment]
Thank you for letting me know.
I changed targets of revert commit to only code for environment variables.

**Comment by scottchiefbaker** [comment]
@pxsta Oh great... that'll make it a lot easier to merge. I've never used the MySQL plugin, can you elaborate on exactly what this fixes and I'll see about getting it reverted. This issue is the last major hurdle to getting 0.7.3 out the door.

**Comment by pxsta** [comment]
This enables us to pass the arguments to plugins through environment variables named "DSTAT_MYSQL_HOST", "DSTAT_MYSQL_PORT", and "DSTAT_MYSQL_SOCKET".
It would make the plugins able to connect to MySQL which runs on remote machines.

For example, first, I run MySQL on machine A(192.168.1.2)
Second, I run dstat on machine B(192.168.1.3)
The plugins of dstat have to connect to MySQL on 192.168.1.2 rather than on 192.168.1.3.
Without this revert commit, we cannot pass "192.168.1.2" to plugins through environment variables, so they uses the default value(127.0.0.1=192.168.1.3) and they cannot connect to MySQL.

"mysql_port" and "mysql_socket" are the same as "mysql_host".(Without this commit, we cannot pass any variables to plugins through environment variables and they cannot connect to MySQL).

**Comment by scottchiefbaker** [comment]
@carlhu since you authored fe5f916, will this work for you?

**Pull request merged**
