### PR TITLE
feat: jvm heap monitor

### PR DESCRIPTION
**Pull request by ioggstream**
This plugins monitor jvm heap and classes usage.

Simple jstat counters: heap and perm/meta space:

```
# dstat --jvm-stat -I JVM_PID 5;
```

With jcmd counters, extensible version with some overhead: 

```
# dstat  --noupdate --jvm-full -I $JVM_PID 5;
```

Feedback welcome.

### CODE REVIEW

**Comment by dagwieers** [comment]
Thanks for your contribution.

I noticed you are *hijacking* the interrupt list to specify a PID and I am not in favor of this.
Unfortunately at this time there is no way for a plugin to add additional options, or activate specific code from the main program. This is something on my list of things to do since a long time, but hasn't happened.

Currently plugins use environment variables to feed information in from, which is suboptimal.

**Comment by scottchiefbaker** [comment]
By *hijacking* you mean he's using `-I` which is already in use? 

```
       -I 5,10
              include interrupt 5 and 10 (when using -i/--int)
```

**Comment by ioggstream** [comment]
Hi @dagwieers,

I wasn't able to find a different solution for passing arguments :(

I saw the hijacking approach in other modules: if the `-I` is the only thing that prevents merging, it's fine for me to modify it.

Please let me know, and thank you for this magic piece of software ;)

Peace,
R.

**Comment by scottchiefbaker** [comment]
I think ultimately this is same issue as #93. We need a mechanism to allow the user to send data in to a plugin. Currently the only way is via environment variables, which are ugly and non-intuitive.

    JVM_OPTS=15349 dstat --all --time --jvm--full

Is just not an intuitive way to do that.

**Comment by ioggstream** [comment]
@dagwieers @scottchiefbaker  I'm no more an hijacker ;) Is it fine now? 

Peace,
R.

**Comment by dagwieers** [comment]
@ioggstream Yes, this looks better. Although @scottchiefbaker is right, we need a better way for plugins to accept information. Thanks !

**Comment by dagwieers** [comment]
Thanks for your contribution !

**Pull request merged**
